"""empty message

Revision ID: 520bb0cc4428
Revises: 
Create Date: 2021-03-24 10:47:12.958345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520bb0cc4428'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital_details',
    sa.Column('hid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospital_group', sa.String(length=500), nullable=False),
    sa.Column('hospital_name', sa.String(length=500), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('hid')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=500), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('access_to', sa.String(length=500), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('hospital_details')
    # ### end Alembic commands ###
